export const currencyName = {
AED: "United Arab Emirates dirham",
AFA: "Afghan afghani",
AFN: "Afghan afghani",
ALL: "Albanian lek",
AMD: "Armenian dram",
ANG: "Netherlands Antillean guilder",
AOA: "Angolan kwanza",
AON: "Angolan new kwanza",
ARS: "Argentine peso",
ATS: "Austrian schilling",
AUD: "Australian dollar",
AWG: "Aruban florin",
AZN: "Azerbaijani manat",
BAM: "Bosnia and Herzegovina convertible mark",
BBD: "Barbados dollar",
BDT: "Bangladeshi taka",
BEF: "Belgian franc",
BGN: "Bulgarian lev",
BHD: "Bahraini dinar",
BIF: "Burundian franc",
BND: "Brunei dollar",
BOB: "Boliviano",
BRL: "Brazilian real",
BSD: "Bahamian dollar",
BWP: "Botswana pula",
BYB: "Belarusian ruble",
BYN: "Belarusian ruble",
BYR: "Belarusian ruble",
BZD: "Belize dollar",
CAD: "Canadian dollar",
CDF: "Congolese franc",
CHF: "Swiss franc",
CLP: "Chilean peso",
CNY: "Renminbi (Chinese) yuan",
COP: "Colombian peso",
CRC: "Costa Rican colon",
CSD: "Serbian dinar",
CVE: "Cape Verdean escudo",
CYP: "Cypriot pound",
CZK: "Czech koruna",
DJF: "Djiboutian franc",
DKK: "Danish krone",
DOP: "Dominican peso",
DZD: "Algerian dinar",
EEK: "Estonian kroon",
EGP: "Egyptian pound",
ERN: "Eritrean nakfa",
ESP: "Spanish peseta",
ETB: "Ethiopian birr",
EUR: "Euro",
FIM: "Finnish markka",
FJD: "Fiji dollar",
FRF: "French franc",
GBP: "Pound sterling",
GEL: "Georgian lari",
GHC: "Ghanaian cedi",
GHS: "Ghanaian cedi",
GIP: "Gibraltar pound",
GMD: "Gambian dalasi",
GNF: "Guinean franc",
GRD: "Greek drachma",
GTQ: "Guatemalan quetzal",
GYD: "Guyanese dollar",
HKD: "Hong Kong dollar",
HNL: "Honduran lempira",
HRK: "Croatian kuna",
HTG: "Haitian gourde",
HUF: "Hungarian forint",
IDR: "Indonesian rupiah",
IEP: "Irish pound",
ILS: "Israeli new shekel",
INR: "Indian rupee",
IQD: "Iraqi dinar",
IRR: "Iranian rial",
ISK: "Icelandic króna",
ITL: "Italian lira",
JMD: "Jamaican dollar",
JOD: "Jordanian dinar",
JPY: "Japanese yen",
KES: "Kenyan shilling",
KGS: "Kyrgyzstani som",
KHR: "Cambodian riel",
KMF: "Comoro franc",
KRW: "South Korean won",
KWD: "Kuwaiti dinar",
KZT: "Kazakhstani tenge",
LAK: "Lao kip",
LBP: "Lebanese pound",
LKR: "Sri Lankan rupee",
LRD: "Liberian dollar",
LSL: "Lesotho loti",
LTL: "Lithuanian litas",
LUF: "Luxembourg franc",
LVL: "Latvian lats",
LYD: "Libyan dinar",
MAD: "Moroccan dirham",
MDL: "Moldovan leu",
MGA: "Malagasy ariary",
MGF: "Malagasy franc",
MKD: "Macedonian denar",
MMK: "Myanmar kyat",
MNT: "Mongolian tögrög",
MOP: "Macanese pataca",
MRO: "Mauritanian ouguiya",
MRU: "Mauritanian ouguiya",
MTL: "Maltese lira",
MUR: "Mauritian rupee",
MVR: "Maldivian rufiyaa",
MWK: "Malawian kwacha",
MXN: "Mexican peso",
MYR: "Malaysian ringgit",
MZM: "Mozambican metical",
MZN: "Mozambican metical",
NAD: "Namibian dollar",
NGN: "Nigerian naira",
NIO: "Nicaraguan córdoba",
NLG: "Dutch guilder",
NOK: "Norwegian krone",
NPR: "Nepalese rupee",
NZD: "New Zealand dollar",
OMR: "Omani rial",
PAB: "Panamanian balboa",
PEN: "Peruvian sol",
PGK: "Papua New Guinean kina",
PHP: "Philippine peso",
PKR: "Pakistani rupee",
PLN: "Polish złoty",
PTE: "Portuguese escudo",
PYG: "Paraguayan guaraní",
QAR: "Qatari riyal",
ROL: "Romanian leu",
RON: "Romanian leu",
RSD: "Serbian dinar",
RUB: "Russian ruble",
RWF: "Rwandan franc",
SAR: "Saudi riyal",
SBD: "Solomon Islands dollar",
SCR: "Seychelles rupee",
SDD: "Sudanese dinar",
SDG: "Sudanese pound",
SEK: "Swedish krona/kronor",
SGD: "Singapore dollar",
SIT: "Slovenian tolar",
SKK: "Slovak koruna",
SLE: "Sierra Leonean leone",
SLL: "Sierra Leonean leone",
SOS: "Somali shilling",
SRD: "Surinamese dollar",
SRG: "Suriname guilder",
SSP: "South Sudanese pound",
STD: "São Tomé and Príncipe dobra",
STN: "São Tomé and Príncipe dobra",
SVC: "Salvadoran colón",
SYP: "Syrian pound",
SZL: "Swazi lilangeni",
THB: "Thai baht",
TJS: "Tajikistani somoni",
TMT: "Turkmenistan manat",
TND: "Tunisian dinar",
TOP: "Tongan paanga",
TRL: "Turkish lira",
TRY: "Turkish lira",
TTD: "Trinidad and Tobago dollar",
TWD: "New Taiwan dollar",
TZS: "Tanzanian shilling",
UAH: "Ukrainian hryvnia",
UGX: "Ugandan shilling",
USD: "United States dollar",
UYU: "Uruguayan peso",
UZS: "Uzbekistan som",
VEB: "Venezuelan bolívar",
VEF: "Venezuelan bolívar fuerte",
VES: "Venezuelan bolívar soberano",
VND: "Vietnamese đồng",
VUV: "Vanuatu vatu",
WST: "Samoan tala",
XAF: "CFA franc BEAC",
XAU: "Gold (one troy ounce)",
XCD: "East Caribbean dollar",
XDR: "Special drawing rights International Monetary Fund",
XOF: "CFA franc BCEAO",
XPF: "CFP franc (franc Pacifique)",
YER: "Yemeni rial",
YUM: "Yugoslav dinar",
ZAR: "South African rand",
ZMK: "Zambian kwacha",
ZMW: "Zambian kwacha",
ZWD: "Zimbabwean dollar",
ZWL: "Zimbabwean dollar",
ZWN: "Zimbabwean dollar",
ZWR: "Zimbabwean dollar",
};
